spring:
  application:
    name: social
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5433/social
    hikari:
      keepalive-time: 60000
  jpa:
    open-in-view: true
  flyway:
    locations: classpath:migration
  jackson:
    default-property-inclusion: non_empty
  cache:
    type: redis
    host: localhost
    port: 6379

server:
  port: 8087
  shutdown: graceful
  forward-headers-strategy: framework

app:
  jwt:
    expiration-ms: 1_800_000